### ISSUE TITLE
deploy to amm.agoric.app

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-amm#16]
I think @samsiegart took the ball on this, but if not... maybe @arirubinstein is interested to help?

similar to https://github.com/Agoric/dapp-treasury/blob/main/.github/workflows/deploy-treasury.yml

I see we have https://github.com/Agoric/dapp-amm/blob/main/.github/workflows/deploy-treasury.yml.DISABLED

cc @rowgraus @Tartuffo

**Comment by samsiegart** [comment]
This is completed
