### ISSUE TITLE
"Add liquidity" gives me all the liquidity for the pool

### ISSUE THREAD

**Issue by samsiegart** [Agoric/dapp-amm#8]
I wanted just 10 LP tokens, but got millions. When I "remove liquidity" and remove all of them, it works and I become very rich. For some reason, the UI says I own a "50%" share of the pool but I seem to own 100%.

![alltheliquidity](https://user-images.githubusercontent.com/8848650/162107935-af231a73-898c-40a3-b508-40f3278e3fc2.PNG)
![50percent](https://user-images.githubusercontent.com/8848650/162107937-bcc97d2a-e823-4e77-b586-9a71487babed.PNG)

**Comment by samsiegart** [comment]
@Chris-Hibbert I believe this may be a contract bug

**Comment by Chris-Hibbert** [comment]
Fixed by https://github.com/Agoric/agoric-sdk/pull/5091
